# Generated by Django 4.1.5 on 2023-01-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
