# Generated by Django 4.1.5 on 2023-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_coupon_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire',
            field=models.DateTimeField(),
        ),
    ]
