# Generated by Django 4.1.5 on 2023-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
