# Generated by Django 4.1.5 on 2023-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_colorvariant_sizevariant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', "Men's Dresses"), ('2', "Women's Dresses"), ('3', "Baby's Dresses"), ('4', 'Shirts'), ('5', 'Jeans'), ('6', 'Furniture/Equipment'), ('7', 'Digital Products'), ('8', 'Watches'), ('9', 'Household'), ('10', 'MakeUp Products'), ('11', 'Jackets'), ('12', 'Shoes')], default='1', max_length=20),
        ),
    ]
