# Generated by Django 4.1.5 on 2023-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_information_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.TextField(max_length=2000, null='None'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=150, null='None'),
        ),
    ]
