# Generated by Django 4.1.5 on 2023-01-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_favourite_favourite'),
        ('store', '0017_product_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='customer.customer'),
        ),
    ]
