# Generated by Django 4.1.5 on 2023-01-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
