# Generated by Django 4.1.5 on 2023-01-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
