# Generated by Django 4.1.5 on 2023-01-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
