# Generated by Django 4.1.5 on 2023-02-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_favorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorie',
        ),
    ]
