# Generated by Django 4.1.5 on 2023-02-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_delete_favorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
