# Generated by Django 4.2.3 on 2023-08-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sizevariant',
            name='price',
        ),
    ]
