# Generated by Django 4.2.3 on 2023-08-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_cart_color_varient_remove_cart_size_varient'),
        ('store', '0045_colorvariant_price_sizevariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
