# Generated by Django 4.2.3 on 2023-09-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_review_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
