# Generated by Django 4.2.3 on 2023-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
