# Generated by Django 4.2.3 on 2023-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.IntegerField(default=0),
        ),
    ]
