# Generated by Django 4.2.3 on 2023-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_product_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
