# Generated by Django 4.1.5 on 2023-02-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_favourite_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
