# Generated by Django 4.1.5 on 2023-02-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
