# Generated by Django 4.1.5 on 2023-02-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_delete_favorite'),
        ('customer', '0011_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='store.product'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='customer.customer'),
        ),
    ]
