# Generated by Django 4.2.3 on 2023-08-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_colorvariant_price_sizevariant_price'),
        ('customer', '0014_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.colorvariant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sizevariant'),
        ),
    ]
