# Generated by Django 4.2.3 on 2023-08-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_cart_color_varient_cart_size_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color_varient',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size_varient',
        ),
    ]
