# Generated by Django 4.2.3 on 2023-08-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_colorvariant_sizevariant_product_color_variant_and_more'),
        ('customer', '0016_remove_cart_color_varient_remove_cart_size_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.colorvariant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sizevariant'),
        ),
    ]
