# Generated by Django 4.2.3 on 2023-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='payment_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
