# Generated by Django 4.2.3 on 2023-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_ordered_address_ordered_payment_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
